### Site metadata

# Don't make the title longer than this, otherwise it gets covered in mobile view.
title: cass deckard
description: cass deckard dot github dot io

github_username: cassdeckard
linkedin_username: cass-deckard
rss: RSS

### Build settings

url: https://cassdeckard.github.io
repository_name: /cassdeckard.github.io
baseurl: /

permalink: pretty

remote_theme: jekyll/minima

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - docs/
  - vendor/
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
