### Site metadata

# Don't make the title longer than this, otherwise it gets covered in mobile view.
title: InfinitySum Game Collective
description: We specialize in games that explore the convergence of art, math, language, cognition, and social justice.

github_username: infinitysum
rss: RSS

### Build settings

url: https://infinitysum.github.io
repository_name: /infinitysum.github.io
baseurl: /

permalink: pretty

remote_theme: jekyll/minima

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - docs/
  - vendor/
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
